-- AlterTable
ALTER TABLE "User" ADD COLUMN "gender" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "ageRange" TEXT NOT NULL DEFAULT '';
ALTER TABLE "User" ADD COLUMN "appearanceDesc" TEXT NOT NULL DEFAULT '';
